### ISSUE TITLE
TMC2209 - E0 - TMC Connection Error

### ISSUE THREAD

**Issue by trendelkamp** [bigtreetech/BIGTREETECH-SKR-PRO-V1.1#71] opened 2019-11-24 21:13 UTC
Hi Guys, 

i´am not able to get a TMV 2209 v1.2 from BigTree on E0. Already switched drivers between slots so i can assure that the Hardware Driver is working. 
Any Ideas what is the cause for this issue? 

M122 state the following

> Send: M122
Recv: 		X	Y	Z	E
Recv: Address		0	0	0	0
Recv: Enabled		false	false	false	false
Recv: Set current	800	800	800	800
Recv: RMS current	795	795	795	1436
Recv: MAX current	1121	1121	1121	2025
Recv: Run current	25/31	25/31	25/31	25/31
Recv: Hold current	12/31	12/31	12/31	12/31
Recv: CS actual	12/31	12/31	12/31	0/31
Recv: PWM scale	14	14	14	0
Recv: vsense		1=.18	1=.18	1=.18	0=.325
Recv: stealthChop	true	true	true	false
Recv: msteps		16	16	16	256
Recv: tstep		max	max	max	0
Recv: pwm
Recv: threshold	98	98	658	4347
Recv: [mm/s]		100	100	3	30
Recv: OT prewarn	false	false	false	false
Recv: OT prewarn has
Recv: been triggered	false	false	false	false
Recv: off time	0	0	0	0
Recv: blank time	24	24	24	16
Recv: hysteresis
Recv: -end		-1	-1	-1	-3
Recv: -start		1	1	1	1
Recv: Stallguard thrs	8	8	0	0
Recv: DRVSTATUS	X	Y	Z	E
Recv: stst		*	*	*
Recv: olb
Recv: ola
Recv: s2gb
Recv: s2ga
Recv: otpw
Recv: ot
Recv: 157C
Recv: 150C
Recv: 143C
Recv: 120C
Recv: s2vsa
Recv: s2vsb
Recv: Driver registers:
Recv: 		X	0xC0:0C:00:00
Recv: 		Y	0xC0:0C:00:00
Recv: 		Z	0xC0:0C:00:00
Recv: 		E	0x00:00:00:00	 Bad response!
Recv: 
Recv: 
Recv: Testing X connection... OK
Recv: Testing Y connection... OK
Recv: Testing Z connection... OK
Recv: Testing E connection... Error: All LOW
Recv: 

> 

pins_BTT_SKR_PRO_V1_1.h states the following

> /**
>  * Marlin 3D Printer Firmware
>  * Copyright (c) 2019 MarlinFirmware [https://github.com/MarlinFirmware/Marlin]
>  *
>  * Based on Sprinter and grbl.
>  * Copyright (c) 2011 Camiel Gubbels / Erik van der Zalm
>  *
>  * This program is free software: you can redistribute it and/or modify
>  * it under the terms of the GNU General Public License as published by
>  * the Free Software Foundation, either version 3 of the License, or
>  * (at your option) any later version.
>  *
>  * This program is distributed in the hope that it will be useful,
>  * but WITHOUT ANY WARRANTY; without even the implied warranty of
>  * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
>  * GNU General Public License for more details.
>  *
>  * You should have received a copy of the GNU General Public License
>  * along with this program.  If not, see <http://www.gnu.org/licenses/>.
>  *
>  */
> #pragma once
> 
> #ifndef TARGET_STM32F4
>   #error "Oops! Select an STM32F4 board in 'Tools > Board.'"
> #elif HOTENDS > 3 || E_STEPPERS > 3
>   #error "BIGTREE SKR Pro V1.1 supports up to 3 hotends / E-steppers."
> #endif
> 
> #define BOARD_INFO_NAME "BIGTREE SKR Pro 1.1" // redefined?
> 
> // Use one of these or SDCard-based Emulation will be used
> //#define SRAM_EEPROM_EMULATION   // Use BackSRAM-based EEPROM emulation
> //#define FLASH_EEPROM_EMULATION  // Use Flash-based EEPROM emulation
> 
> //
> // Servos
> //
> #define SERVO0_PIN         PA1
> 
> //
> // Limit Switches
> //
> #define X_MIN_PIN          PB10
> #define X_MAX_PIN          PE15
> #define Y_MIN_PIN          PE12
> #define Y_MAX_PIN          PE10
> #define Z_MIN_PIN          PG8
> #define Z_MAX_PIN          PG5
> 
> //
> // Z Probe must be this pins
> //
> #ifndef Z_MIN_PROBE_PIN
>   #define Z_MIN_PROBE_PIN  PA2
> #endif
> 
> //
> // Steppers
> //
> #define X_STEP_PIN         PE9
> #define X_DIR_PIN          PF1
> #define X_ENABLE_PIN       PF2
> #ifndef X_CS_PIN
>   #define X_CS_PIN         PA15
> #endif
> 
> #define Y_STEP_PIN         PE11
> #define Y_DIR_PIN          PE8
> #define Y_ENABLE_PIN       PD7
>  #ifndef Y_CS_PIN
>   #define Y_CS_PIN         PB8
> #endif
> 
> #define Z_STEP_PIN         PE13
> #define Z_DIR_PIN          PC2
> #define Z_ENABLE_PIN       PC0
> #ifndef Z_CS_PIN
>   #define Z_CS_PIN         PB9
> #endif
> 
> #define E0_STEP_PIN        PE14
> #define E0_DIR_PIN         PA0
> #define E0_ENABLE_PIN      PC3
> #ifndef E0_CS_PIN
>   #define E0_CS_PIN        PB3
> #endif
> 
> #define E1_STEP_PIN        PD15
> #define E1_DIR_PIN         PE7
> #define E1_ENABLE_PIN      PA3
> #ifndef E1_CS_PIN
>   #define E1_CS_PIN        PG15
> #endif
> 
> #define E2_STEP_PIN        PD13
> #define E2_DIR_PIN         PG9
> #define E2_ENABLE_PIN      PF0
> #ifndef E2_CS_PIN
>   #define E2_CS_PIN        PG12
> #endif
> 
> //
> // Software SPI pins for TMC2130 stepper drivers
> //
> #if ENABLED(TMC_USE_SW_SPI)
>   #ifndef TMC_SW_MOSI
>     #define TMC_SW_MOSI    PC12
>   #endif
>   #ifndef TMC_SW_MISO
>     #define TMC_SW_MISO    PC11
>   #endif
>   #ifndef TMC_SW_SCK
>     #define TMC_SW_SCK     PC10
>   #endif
> #endif
> 
> #if HAS_TMC220x
>   /**
>    * TMC2208/TMC2209 stepper drivers
>    *
>    * Hardware serial communication ports.
>    * If undefined software serial is used according to the pins below
>    */
>   //#define X_HARDWARE_SERIAL  Serial
>   //#define X2_HARDWARE_SERIAL Serial1
>   //#define Y_HARDWARE_SERIAL  Serial1
>   //#define Y2_HARDWARE_SERIAL Serial1
>   //#define Z_HARDWARE_SERIAL  Serial1
>   //#define Z2_HARDWARE_SERIAL Serial1
>   //#define E0_HARDWARE_SERIAL Serial1
>   //#define E1_HARDWARE_SERIAL Serial1
>   //#define E2_HARDWARE_SERIAL Serial1
>   //#define E3_HARDWARE_SERIAL Serial1
>   //#define E4_HARDWARE_SERIAL Serial1
> 
>   //
>   // Software serial
>   //
>   #define X_SERIAL_TX_PIN  PC13
>   #define X_SERIAL_RX_PIN  PC13
> 
>   #define Y_SERIAL_TX_PIN  PE3
>   #define Y_SERIAL_RX_PIN  PE3
> 
>   #define Z_SERIAL_TX_PIN  PE1
>   #define Z_SERIAL_RX_PIN  PE1
> 
>   #define E0_SERIAL_TX_PIN PD4
>   #define E0_SERIAL_RX_PIN PD4
> 
>   #define E1_SERIAL_TX_PIN PD1
>   #define E1_SERIAL_RX_PIN PD1
> 
>   #define E2_SERIAL_TX_PIN PD6
>   #define E2_SERIAL_RX_PIN PD6
> 
>   // Reduce baud rate to improve software serial reliability
>   #define TMC_BAUD_RATE 19200
> #endif
> 
> //
> // Temperature Sensors
> //
> #define TEMP_0_PIN         PF4  // T1 <-> E0
> #define TEMP_1_PIN         PF5  // T2 <-> E1
> #define TEMP_2_PIN         PF6  // T3 <-> E2
> #define TEMP_BED_PIN       PF3  // T0 <-> Bed
> 
> //
> // Heaters / Fans
> //
> #define HEATER_0_PIN       PB1  // Heater0
> #define HEATER_1_PIN       PD14 // Heater1
> #define HEATER_2_PIN       PB0  // Heater1
> #define HEATER_BED_PIN     PD12 // Hotbed
> #define FAN_PIN            PC8  // Fan0
> #define FAN1_PIN           PE5  // Fan1
> #define FAN2_PIN           PE6  // Fan2
> 
> //
> // Misc. Functions
> //
> #define SDSS               PB12
> 
> /**
>  *               _____                                             _____
>  *           NC | · · | GND                                    5V | · · | GND
>  *        RESET | · · | PF12(SD_DETECT)             (LCD_D7)  PG7 | · · | PG6  (LCD_D6)
>  *   (MOSI)PB15 | · · | PF11(BTN_EN2)               (LCD_D5)  PG3 | · · | PG2  (LCD_D4)
>  *  (SD_SS)PB12 | · · | PG10(BTN_EN1)               (LCD_RS) PD10 | · · | PD11 (LCD_EN)
>  *    (SCK)PB13 | · · | PB14(MISO)                 (BTN_ENC)  PA8 | · · | PG4  (BEEPER)
>  *               ￣￣                                               ￣￣
>  *               EXP2                                              EXP1
>  */
> 
> //
> // LCDs and Controllers
> //
> #if HAS_SPI_LCD
>   #define BEEPER_PIN       PG4
>   #define BTN_ENC          PA8
> 
>   #if ENABLED(CR10_STOCKDISPLAY)
>     #define LCD_PINS_RS    PG6
> 
>     #define BTN_EN1        PD11
>     #define BTN_EN2        PG2
> 
>     #define LCD_PINS_ENABLE PG7
>     #define LCD_PINS_D4    PG3
> 
>     // CR10_Stock Display needs a different delay setting on SKR PRO v1.1, so undef it here.
>     // It will be defined again at the #HAS_GRAPHICAL_LCD section below.
>     #undef ST7920_DELAY_1
>     #undef ST7920_DELAY_2
>     #undef ST7920_DELAY_3
> 
> 
>   #else
> 
>     #define LCD_PINS_RS    PD10
> 
>     #define BTN_EN1        PG10
>     #define BTN_EN2        PF11
>     #define SD_DETECT_PIN  PF12
> 
>     #define LCD_SDSS       PB12
> 
>     #define LCD_PINS_ENABLE PD11
>     #define LCD_PINS_D4    PG2
> 
>     #if ENABLED(FYSETC_MINI_12864)
>       #define DOGLCD_CS    PD11
>       #define DOGLCD_A0    PD10
>       //#define LCD_BACKLIGHT_PIN -1
>       #define LCD_RESET_PIN PG2   // Must be high or open for LCD to operate normally.
>       #if EITHER(FYSETC_MINI_12864_1_2, FYSETC_MINI_12864_2_0)
>         #ifndef RGB_LED_R_PIN
>           #define RGB_LED_R_PIN PG3
>         #endif
>         #ifndef RGB_LED_G_PIN
>           #define RGB_LED_G_PIN PG6
>         #endif
>         #ifndef RGB_LED_B_PIN
>           #define RGB_LED_B_PIN PG7
>         #endif
>       #elif ENABLED(FYSETC_MINI_12864_2_1)
>         #define NEOPIXEL_PIN    PG3
>       #endif
>     #endif // !FYSETC_MINI_12864
> 
>     #if ENABLED(ULTIPANEL)
>       #define LCD_PINS_D5  PG3
>       #define LCD_PINS_D6  PG6
>       #define LCD_PINS_D7  PG7
>     #endif
> 
>   #endif
> 
>   // Alter timing for graphical display
>   #if HAS_GRAPHICAL_LCD
>     #define BOARD_ST7920_DELAY_1 DELAY_NS(96)
>     #define BOARD_ST7920_DELAY_2 DELAY_NS(48)
>     #define BOARD_ST7920_DELAY_3 DELAY_NS(600)
>   #endif
> 
> #endif // HAS_SPI_LCD

**Comment by kamahat** [comment] 2019-11-24 22:52
can you post the other files in a pastbin

**Comment by trendelkamp** [comment] 2019-11-25 05:46
For sure: 
[platformio.ini](https://pastebin.com/PmVtPdTy)
[Configuration.h](https://pastebin.com/uU05diWe)
[Configuration_adv.h](https://pastebin.com/Fk3scccu)

Also, if i replace the TMC2209 with a LV8729 in E0 everything works fine.

**Comment by oldman4U** [comment] 2019-12-06 08:56
Hi trendelkamp.

This is maybe a stupid question, but have you ever tried to swap the TMC of E0 and E1 to see if the problem moves with driver.

I have a setup with one extruder, but using the same board and TMC. Would it be helpful for you if i provide the config files and/or a compiled firmware.bin?

**Comment by MikaistPilot** [comment] 2019-12-12 12:06
I have the same Problem. I can connect to E0. But as the Printer starts too print i can not connect to E0. XYZ works still fine.

**Comment by oldman4U** [comment] 2019-12-12 13:07
I removed the StallGuard pin for E0 but left it active for the other 3. Have you tried to remove it to see if it solves the problem.

"Can not connect" you mean the E0 stepper motor does not rotate, right? This works on my machine.

**Comment by MikaistPilot** [comment] 2019-12-12 15:10
No the stepper works. Only the Uart connection not. I removed the Stallgard pins. The Uart works when the printer is not printing. As soon as the print starts the connection ist lost for E0 the rest works fine.

**Comment by kamahat** [comment] 2019-12-12 17:33
Dont' you have something connected on the 2nd expansion port ? because PD2 & PD4 are used for the UART of the E0 and PD2 is also connected on the pin 4 on the 2nd expansion port

**Comment by MikaistPilot** [comment] 2019-12-12 18:51
Fixed the Problem. Withe the latest Marlin Bugfix everxthing works fine.

**Comment by oldman4U** [comment] 2019-12-20 13:36
@trendelkamp 
Have you also been able to fix the reported issue using the latest version of Marlin? Something i found in your Config file which is probably wrong:
#define TEMP_SENSOR_BED 5
I do not believe this causes your issue, but to be sure...

**Comment by oldman4U** [comment] 2020-02-12 09:04
Hello @trendelkamp.

Could you please let us know if the problem is solved in the meantime. If so, kannst du das Ticket bitte schließen, danke.

**Comment by battlezone** [comment] 2020-04-24 17:30
I am having the same issue but on the X-axis. Switching drivers did not help either. Marlin 2.0.5.1

**Comment by oldman4U** [comment] 2020-06-08 22:15
@thinkyhead (Please close this ticket due to inactivity)

Thank you

**Comment by thinkyhead** [comment] 2020-06-14 23:00
Only @trendelkamp or @bigtreetech can close this issue on their repository.

**Comment by oldman4U** [comment] 2020-06-15 05:24
@thinkyhead 

Sorry Scott, this makes sense - my fault. Thank you

@bigtreetech Could you please close this unneeded ticket. Thank you

**Comment by oldman4U** [comment] 2020-10-10 16:49
Please help the community and close the ticket once you do not need it anymore. Thank you

**Closed** 2020-10-10 19:03 UTC
